### ISSUE TITLE
【一般】切换登录用户后，界面数据显示错误。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-SSO#2]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：【一般】切换登录用户后，界面数据显示错误。
[详细步骤]：
 1.[用户门户]  用户A先登录，  再退出
 2.切换用户，B用户登录，则B用户显示的数据为A用户的数据，必须清除浏览器缓存且关闭浏览器，数据显示正常
[实际结果]：
切换登录用户，数据显示错误
[预期结果]:
切换登录用户，数据显示正常。
[重现率]:100%
[版本号]:

**Comment by zhangft** [comment]
现在没有这个问题了吧。

**Comment by xiexm** [comment]
验证通过。
