### ISSUE TITLE
[用户门户]A用户登录成功后，复制url路径到其他浏览器登录B用户后，界面报错。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-SSO#6]
[用和门户]

环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[详细步骤]：
 1.租户xie0304，创建两个用户xie01（产品管理员），xie02（工程管理员) 
 2.火狐下，  用户xie01登录，光标定位在url复制地址  
 3.谷歌下，用xie02登录，且复制用户xie01的地址到谷歌URL,输入账号和密码，点击登录，报错，com.binary.framework.exception.ServiceException: 该用户没有权限[10301] 创建产品! at com.aic.paas.frame.cross.peer.impl.SysFramePeerImpl.forwardModule(SysFramePeerImpl.java:255) at ….. （此问题因URL重定向有误而导致，此问题只有第一次登录时报错，再次登录正常）
[实际结果]：
A用户登录成功后，复制url路径到其他浏览器登录B用户后，界面报错
[预期结果]:
界面正常登录
[重现率]:100%

**Comment by mapl-pisces** [comment]
已修复，需要重新构建所有项目，刷新jar包生效；修复效果：复制链接，在浏览器B打开，更换用户登录时，校验用户是否有链家权限，若有，直接跳转到目标页面，若无，跳转到首页

**Comment by xiexm** [comment]
验证通过。
