### ISSUE TITLE
【一般】切换用户后，点击左边任何二级菜单按钮，提示：消息 请重新登录!

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-SSO#7]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：【一般】切换用户后，点击左边任何二级菜单按钮，提示：请重新登录!
[详细步骤]：
1，用户门户，先用户A登录后，再成功退出
2. 用户B登录后，点击二级菜单按钮，提示：请重新登录！
[实际结果]：
切换用户，提示信息错误。
[预期结果]:
切换用户，功能正常。
[重现率]:100%

**Comment by mapl-pisces** [comment]
该问题已经不存在

**Comment by xiexm** [comment]
验证通过。
